# Generated by Django 2.2.2 on 2019-06-17 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('step_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='steps',
            options={'verbose_name_plural': 'Steps'},
        ),
    ]
